In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Housing.csv')
print(df)

          price  area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000.0  7420       4.0        2.0      3.0      yes        no
1    12250000.0  8960       4.0        4.0      4.0      yes        no
2    12250000.0  9960       3.0        2.0      2.0      yes        no
3    12215000.0  7500       4.0        2.0      2.0      yes        no
4    11410000.0  7420       4.0        1.0      2.0      yes       yes
..          ...   ...       ...        ...      ...      ...       ...
540   1820000.0  3000       2.0        1.0      1.0      yes        no
541   1767150.0  2400       3.0        1.0      1.0       no        no
542   1750000.0  3620       2.0        1.0      1.0      yes        no
543   1750000.0  2910       3.0        1.0      1.0       no        no
544   1750000.0  3850       3.0        1.0      2.0      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2      yes
1         no              no             yes        3       no
2        yes              no              no        2      yes
3        yes              no             yes        3      yes
4        yes              no             yes        2       no
..       ...             ...             ...      ...      ...
540      yes              no              no        2       no
541       no              no              no        0       no
542       no              no              no        0       no
543       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
..               ...
540      unfurnished
541   semi-furnished
542      unfurnished
543        furnished
544      unfurnished

[545 rows x 13 columns]

In [ ]:

#selecting\accessing column
df[["price","area","bedrooms","bathrooms","basement"]]

          price  area  bedrooms  bathrooms basement
0    13300000.0  7420       4.0        2.0       no
1    12250000.0  8960       4.0        4.0       no
2    12250000.0  9960       3.0        2.0      yes
3    12215000.0  7500       4.0        2.0      yes
4    11410000.0  7420       4.0        1.0      yes
..          ...   ...       ...        ...      ...
540   1820000.0  3000       2.0        1.0      yes
541   1767150.0  2400       3.0        1.0       no
542   1750000.0  3620       2.0        1.0       no
543   1750000.0  2910       3.0        1.0       no
544   1750000.0  3850       3.0        1.0       no

[545 rows x 5 columns]

In [ ]:
df['area'].mean()
#df['area'].sum()
#df['area'].mim()
#df['area'].max()
df['area'].std()

2170.141022508803

In [ ]:

#select data row wise
df.loc[4]

price               11410000.0
area                      7420
bedrooms                   4.0
bathrooms                  1.0
stories                    2.0
mainroad                   yes
guestroom                  yes
basement                   yes
hotwaterheating             no
airconditioning            yes
parking                      2
prefarea                    no
furnishingstatus     furnished
Name: 4, dtype: object

In [ ]:
#select data index wise
df.iloc[5]

price                   10850000.0
area                          7500
bedrooms                       3.0
bathrooms                      3.0
stories                        1.0
mainroad                       yes
guestroom                       no
basement                       yes
hotwaterheating                 no
airconditioning                yes
parking                          2
prefarea                       yes
furnishingstatus    semi-furnished
Name: 5, dtype: object

In [ ]:
#filtering data
df[df["price"]<11410000.0]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
5,10850000.0,7500,3.0,3.0,1.0,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000.0,8580,4.0,3.0,4.0,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000.0,16200,5.0,3.0,2.0,yes,no,no,no,no,0,no,unfurnished
8,9870000.0,8100,4.0,1.0,2.0,yes,yes,yes,no,yes,2,yes,furnished
9,9800000.0,5750,3.0,2.0,4.0,yes,yes,no,no,yes,1,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000.0,3000,2.0,1.0,1.0,yes,no,yes,no,no,2,no,unfurnished
541,1767150.0,2400,3.0,1.0,1.0,no,no,no,no,no,0,no,semi-furnished
542,1750000.0,3620,2.0,1.0,1.0,yes,no,no,no,no,0,no,unfurnished
543,1750000.0,2910,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
544,1750000.0,3850,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished

In [ ]:
#adding column
df["Price_in_Lakhs"] = df["price"] / 100000
print(df)

          price  area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000.0  7420       4.0        2.0      3.0      yes        no
1    12250000.0  8960       4.0        4.0      4.0      yes        no
2    12250000.0  9960       3.0        2.0      2.0      yes        no
3    12215000.0  7500       4.0        2.0      2.0      yes        no
4    11410000.0  7420       4.0        1.0      2.0      yes       yes
..          ...   ...       ...        ...      ...      ...       ...
540   1820000.0  3000       2.0        1.0      1.0      yes        no
541   1767150.0  2400       3.0        1.0      1.0       no        no
542   1750000.0  3620       2.0        1.0      1.0      yes        no
543   1750000.0  2910       3.0        1.0      1.0       no        no
544   1750000.0  3850       3.0        1.0      2.0      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2      yes
1         no              no             yes        3       no
2        yes              no              no        2      yes
3        yes              no             yes        3      yes
4        yes              no             yes        2       no
..       ...             ...             ...      ...      ...
540      yes              no              no        2       no
541       no              no              no        0       no
542       no              no              no        0       no
543       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus  Price_in_Lakhs
0          furnished        133.0000
1          furnished        122.5000
2     semi-furnished        122.5000
3          furnished        122.1500
4          furnished        114.1000
..               ...             ...
540      unfurnished         18.2000
541   semi-furnished         17.6715
542      unfurnished         17.5000
543        furnished         17.5000
544      unfurnished         17.5000

[545 rows x 14 columns]

In [ ]:
print(df.columns)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
#removing column
#axis =1 used for column,inplace is used for delete permanently
df.drop('area',axis=1,inplace=True,errors="ignore")
print(df)

          price  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000.0       4.0        2.0      3.0      yes        no       no
1    12250000.0       4.0        4.0      4.0      yes        no       no
2    12250000.0       3.0        2.0      2.0      yes        no      yes
3    12215000.0       4.0        2.0      2.0      yes        no      yes
4    11410000.0       4.0        1.0      2.0      yes       yes      yes
..          ...       ...        ...      ...      ...       ...      ...
540   1820000.0       2.0        1.0      1.0      yes        no      yes
541   1767150.0       3.0        1.0      1.0       no        no       no
542   1750000.0       2.0        1.0      1.0      yes        no       no
543   1750000.0       3.0        1.0      1.0       no        no       no
544   1750000.0       3.0        1.0      2.0      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 12 columns]

In [ ]:
# give null values of all columns
df.isnull().sum()

price               3
bedrooms            2
bathrooms           2
stories             1
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
#fill the null values with zero
df.fillna(0)

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000.0,4.0,2.0,3.0,yes,no,no,no,yes,2,yes,furnished
1,12250000.0,4.0,4.0,4.0,yes,no,no,no,yes,3,no,furnished
2,12250000.0,3.0,2.0,2.0,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000.0,4.0,2.0,2.0,yes,no,yes,no,yes,3,yes,furnished
4,11410000.0,4.0,1.0,2.0,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000.0,2.0,1.0,1.0,yes,no,yes,no,no,2,no,unfurnished
541,1767150.0,3.0,1.0,1.0,no,no,no,no,no,0,no,semi-furnished
542,1750000.0,2.0,1.0,1.0,yes,no,no,no,no,0,no,unfurnished
543,1750000.0,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
544,1750000.0,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished

In [ ]:
#remove all NaN values from dataset
df.dropna()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000.0,4.0,2.0,3.0,yes,no,no,no,yes,2,yes,furnished
1,12250000.0,4.0,4.0,4.0,yes,no,no,no,yes,3,no,furnished
2,12250000.0,3.0,2.0,2.0,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000.0,4.0,2.0,2.0,yes,no,yes,no,yes,3,yes,furnished
4,11410000.0,4.0,1.0,2.0,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000.0,2.0,1.0,1.0,yes,no,yes,no,no,2,no,unfurnished
541,1767150.0,3.0,1.0,1.0,no,no,no,no,no,0,no,semi-furnished
542,1750000.0,2.0,1.0,1.0,yes,no,no,no,no,0,no,unfurnished
543,1750000.0,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
544,1750000.0,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.sort_values('price')

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
544,1750000.0,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished
543,1750000.0,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
542,1750000.0,2.0,1.0,1.0,yes,no,no,no,no,0,no,unfurnished
541,1767150.0,3.0,1.0,1.0,no,no,no,no,no,0,no,semi-furnished
540,1820000.0,2.0,1.0,1.0,yes,no,yes,no,no,2,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
2,12250000.0,3.0,2.0,2.0,yes,no,yes,no,no,2,yes,semi-furnished
0,13300000.0,4.0,2.0,3.0,yes,no,no,no,yes,2,yes,furnished
76,NaN,3.0,2.0,3.0,yes,no,no,no,yes,0,yes,furnished
90,NaN,3.0,1.0,2.0,yes,no,no,no,yes,0,no,semi-furnished
122,NaN,4.0,2.0,1.0,yes,no,yes,no,no,1,yes,semi-furnished

In [ ]:
df.sort_index()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000.0,4.0,2.0,3.0,yes,no,no,no,yes,2,yes,furnished
1,12250000.0,4.0,4.0,4.0,yes,no,no,no,yes,3,no,furnished
2,12250000.0,3.0,2.0,2.0,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000.0,4.0,2.0,2.0,yes,no,yes,no,yes,3,yes,furnished
4,11410000.0,4.0,1.0,2.0,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000.0,2.0,1.0,1.0,yes,no,yes,no,no,2,no,unfurnished
541,1767150.0,3.0,1.0,1.0,no,no,no,no,no,0,no,semi-furnished
542,1750000.0,2.0,1.0,1.0,yes,no,no,no,no,0,no,unfurnished
543,1750000.0,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
544,1750000.0,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.head(2)

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000.0,4.0,2.0,3.0,yes,no,no,no,yes,2,yes,furnished
1,12250000.0,4.0,4.0,4.0,yes,no,no,no,yes,3,no,furnished

In [ ]:
df.tail(2)

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
543,1750000.0,3.0,1.0,1.0,no,no,no,no,no,0,no,furnished
544,1750000.0,3.0,1.0,2.0,yes,no,no,no,no,0,no,unfurnished

In [ ]:
pivot_table = df.pivot_table(
    index="furnishingstatus",
    columns="bedrooms",
    values="price",
    aggfunc="mean"
)

print(pivot_table)

bedrooms                1.0           2.0           3.0           4.0  \
furnishingstatus
furnished         3150000.0  4.114250e+06  5.443286e+06  6.953655e+06
semi-furnished          NaN  3.984260e+06  5.038964e+06  5.534989e+06
unfurnished       2275000.0  3.070667e+06  4.443015e+06  4.254250e+06

bedrooms                5.0        6.0
furnishingstatus
furnished         5974500.0  6083000.0
semi-furnished    4095000.0        NaN
unfurnished       6527500.0  3500000.0